spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connection-init-sql: 'set names utf8mb4;'
      connection-timeout: 60000
      maximum-pool-size: 8

logging.level.com.unity.verify.dao: debug

#mybatis:
#  mapperLocations: classpath:mybatis/*.xml
##  typeAliasesPackage: com.unity.verify.entity.*
#  typeHandlersPackage: com.unity.common.base.config.typeHandler
#  configuration:
#    mapUnderscoreToCamelCase: true
#    defaultFetchSize: 50
#    defaultStatementTimeout: 15
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

#mybatis-plus:
#  global-config:
#    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
#    logic-delete-value: 1
#    logic-not-delete-value: 0

mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml
  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.unity.verify.entity.*
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: ID_WORKER
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    refresh: true
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
  #sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
