spring:
#  session:
#    store-type: redis
  redis:
    namespace: sessionRBAC
    flush-mode: on-save
    timeout: 5000D

    jedis:
      pool:
        max-idle: 50
        min-idle: 20
        max-active: 200
        max-wait: 3000D

---
spring:
  profiles: devel
  redis:
      port: 6379
      host: 172.19.1.81
      password: Jingkai123

---

spring:
  profiles: test
  redis:
      port: 6379
      host: 172.19.1.81
      password: Jingkai123
#spring:
#  profiles: test
#  redis:
#    host: 127.0.0.1
#    password: "u2f-3mBt7~Y}DQ=]gX"

---
spring:
  profiles: uat
  redis:
    port: 6379
    host: 172.16.20.14
    password: Jingkai123

---
spring:
  profiles: prod
  redis:
     port: 6379
     host: 192.168.2.61
     password: Jingkai123
