
---
spring.profiles: devel
spring:
  rabbitmq:
    host: 192.168.101.44
    password: admin


---
spring.profiles: test
spring:
  rabbitmq:
    host: 192.168.101.44
    password: admin
---
spring.profiles: uat
spring:
  rabbitmq:
    host: 192.168.101.44
    password: admin
---

spring.profiles: prod
spring:
  rabbitmq:
    host: 192.168.101.44
    password: admin